"""Initial migration: users, nfts, transactions tables

Revision ID: 87de5fad2e40
Revises: 
Create Date: 2025-08-05 23:44:03.108565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87de5fad2e40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('profile_pic', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('nfts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_inr', sa.Float(), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('is_sold', sa.Boolean(), nullable=False),
    sa.Column('is_reserved', sa.Boolean(), nullable=False),
    sa.Column('sold_to_user_id', sa.Integer(), nullable=True),
    sa.Column('contract_address', sa.String(length=255), nullable=True),
    sa.Column('token_id', sa.String(length=255), nullable=True),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sold_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfts_contract_address'), 'nfts', ['contract_address'], unique=False)
    op.create_index(op.f('ix_nfts_id'), 'nfts', ['id'], unique=False)
    op.create_index(op.f('ix_nfts_is_reserved'), 'nfts', ['is_reserved'], unique=False)
    op.create_index(op.f('ix_nfts_is_sold'), 'nfts', ['is_sold'], unique=False)
    op.create_index(op.f('ix_nfts_price_inr'), 'nfts', ['price_inr'], unique=False)
    op.create_index(op.f('ix_nfts_price_usd'), 'nfts', ['price_usd'], unique=False)
    op.create_index(op.f('ix_nfts_sold_to_user_id'), 'nfts', ['sold_to_user_id'], unique=False)
    op.create_index(op.f('ix_nfts_title'), 'nfts', ['title'], unique=False)
    op.create_index(op.f('ix_nfts_token_id'), 'nfts', ['token_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nft_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Enum('INR', 'USD', name='paymentmethod'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'CANCELLED', name='transactionstatus'), nullable=False),
    sa.Column('txn_ref', sa.String(length=255), nullable=True),
    sa.Column('gateway_response', sa.Text(), nullable=True),
    sa.Column('amount', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['nft_id'], ['nfts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_nft_id'), 'transactions', ['nft_id'], unique=False)
    op.create_index(op.f('ix_transactions_payment_method'), 'transactions', ['payment_method'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_txn_ref'), 'transactions', ['txn_ref'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_txn_ref'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payment_method'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_nft_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_nfts_token_id'), table_name='nfts')
    op.drop_index(op.f('ix_nfts_title'), table_name='nfts')
    op.drop_index(op.f('ix_nfts_sold_to_user_id'), table_name='nfts')
    op.drop_index(op.f('ix_nfts_price_usd'), table_name='nfts')
    op.drop_index(op.f('ix_nfts_price_inr'), table_name='nfts')
    op.drop_index(op.f('ix_nfts_is_sold'), table_name='nfts')
    op.drop_index(op.f('ix_nfts_is_reserved'), table_name='nfts')
    op.drop_index(op.f('ix_nfts_id'), table_name='nfts')
    op.drop_index(op.f('ix_nfts_contract_address'), table_name='nfts')
    op.drop_table('nfts')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
